### get developers

GET http://localhost:3000/developers

### get developer 

GET http://localhost:3000/developers/1

### post developer

POST http://localhost:3000/developers
Content-Type: application/json

{
    "name": "izaias ramos",
    "email": "izaias-ramos@gmail.com",
    "dateOfBirth": "2005-05-14"
}

### update developers

PATCH http://localhost:3000/developers/1
Content-Type: application/json

{
    "name": "izaias ramos",
    "email": "izaias@email.com"
}

### delete developers

DELETE http://localhost:3000/developers/1